routes/web.php
<?php

use App\Http\Controllers\FormsController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\TicketController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Form routes
Route::post('kontakt', [FormsController::class, 'contact'])->name('forms.contact');
Route::post('verein/mitgliedschaft', [FormsController::class, 'membership'])->name('forms.membership');

// Default page routes
Route::get('{path?}', PagesController::class)->where('path', '.*');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Builder;

class Post extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['id'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $casts = [
        'date' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('order', function (Builder $builder) {
            $builder->orderBy('date', 'desc');
        });
    }

    public function getPathThumbnailAttribute()
    {
        return sprintf('instagram/thumbnail/%s.jpg', $this->id);
    }

    public function getPathDisplayAttribute()
    {
        return sprintf('instagram/display/%s.jpg', $this->id);
    }
}

resources/views/pages/galerie.blade.php
@extends('layout.main')

@section('title', 'Galerie')
@section('image', asset('images/archive/large/2012_konzert_e.jpg'))
@section('abstract')
    Auf dieser Seite finden Sie einige Schnappschüsse auf dem Vereinsleben.
    Noch mehr aktuelle Bilder gibt es auf <a class="text-white" target="_blank" rel="noreferrer" href="https://www.instagram.com/musikalische.loewen/" >Instagram</a>.
@endsection

@section('main')
    <div class="container mt-5 mb-4">
        <div class="row row-cols-1 row-cols-md-4 g-4" id="lightgallery">
            @php
                $images = glob(public_path('images/archive/small').'/20*.jpg');
                natsort($images);
                $descriptions = [
                    '2010_konzert_afrika' => 'Konzert 2010: Afrika',
                    '2011_bw-musix_balingen' => 'Das Jugendorchester auf dem BWMusix Wettbewerb 2011 in Balingen',
                    '2011_gemeinschaftkonzert_ebernhahn' => 'Gemeinschaftskonzert 2011 mit dem Musikverein Ebernhahn',
                    '2011_kirchturmblasen_niedererbach' => 'Kirchturmblasen im Advent 2011 in Niedererbach',
                    '2011_vereinsausflug_calella' => 'Vereinsausflug 2011 auf das internationalen Oktoberfest nach Calella',
                    '2012_konzert_' => 'Konzert 2012: Concierto de Calella',
                    '2012_konzertreise_thueringen' => 'Konzertreise 2012 nach Thüringen',
                    '2013_heeresmusikkorps_workshop_JO' => 'Das Jugendorchester zu Gast beim Heeresmusikkorps in Koblenz',
                    '2013_vom_westerwald_in_den_wilden_westen' => 'Konzert 2012: Vom Westerwald in den Wilden Westen',
                    '2014_very_british' => 'Konzert 2014: Very British!',
                    '2015_mit_dem_wind_nach_westen' => 'Konzert 2015: Mit dem Wind nach Westen',
                    '2016_carnaval_de_paris' => 'Konzert 2016: Carnaval de Paris',
                    '2016_em_qualifikation_u21' => 'Begleitung eines EM-Qualifikationsspiels der U21 Fußball Nationalmannschaft 2016',
                    '2016_kirmes_nentershausen' => 'Kirmes 2016 in Nentershausen',
                    '2016_vereinsausflug_calella' => 'Vereinsausflug 2016 auf das internationalen Oktoberfest nach Calella',
                    '2016_wir_fuellen_das_stadion_frankfurt' => 'Teilnahme am Weltrekordversuch "Wir füllen das Stadion 2016" in der Commerzbank-Arena in Frankfurt',
                    '2017_karneval' => 'Karneval 2017',
                    '2017_konzert_stratosphaere' => 'Konzert 2017: Stratosphäre',
                    '2017_statosphaere' => 'Konzert 2017: Stratosphäre',
                    '2018_bb' => 'Die Big Band der Bundeswehr 2018 zu Gast in Nenterhausen',
                    '2018_der_musikalische_loewe' => 'Konzert 2018: Der Musikalische Löwe',
                    '2019_kirchturmblasen' => 'Kirchturmblasen Weihnachten 2019 in Nentershausen',
                    '2019_konzert_circus' => 'Konzert 2019: Circus in Nentershausen',
                    '2019_oktoberfest_montabaur' => 'Auftritt auf dem Oktoberfest 2019 in Montabaur',
                    '2019_volkstrauertag' => 'Volkstrauertag 2019',
                    '2019_weihnachtsmarkt' => 'Weihnachtsmarkt 2019 in Limburg',
                    '2020_karneval' => 'Veilchendienstagsumzug 2020 in Heimbach-Weis',
                    '2022_konzert_zu_neuen_horizonten' => 'Konzert 2022: Zu neuen Horizonten',
                    '2023_konzert_klang_der_alpen_gruppenfoto' => 'Konzert 2023: Klang der Alpen',
                    '2023_konzert_klang_der_alpen_plakat' => 'Konzert 2023: Klang der Alpen',
                    '2023_adventskonzert' => 'Adventskonzert 2023'
                ];
            @endphp
            @foreach(array_reverse($images) as $image)
                @php
                    $name = Str::afterLast($image, '/');
                    foreach($descriptions as $key => $description) {
                        if (Str::startsWith($name, $key)) {
                            break;
                        }
                        else {
                            $description = '';
                        }
                    }
                @endphp
                <div class="col">
                    <div class="card shadow-sm">
                        <a href="{{ asset('images/archive/large/'.$name) }}" class="card-img-wrap" data-sub-html="{{ $description }}">
                            <img src="{{ asset('images/archive/small/'.$name) }}" class="card-img-top" alt="{{ $description }}">
                        </a>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        // Initialize lightgallery
        let lightGalleryOptions = {
            selector: '.card-img-wrap',
            download: false,
        };
        lightGallery(document.getElementById('lightgallery'), lightGalleryOptions);
        // Initialize Mansonry
        let masonry = new Masonry(document.getElementById('lightgallery'), {
            itemSelector: '.col',
            percentPosition: true,
        });
        // Layout Masonry after each image loaded
        imagesLoaded(document.getElementById('lightgallery'), function() {
            masonry.layout();
        });
    </script>
@endsection

resources/views/pages/index.blade.php
@extends('layout.base')

@section('navbar-fixed', True)

@section('description', 'Wir sind ein junger Musikverein aus Nentershausen im Westerwald und bieten Ihnen Musik für die verschiedensten Anlässe. Gerne kommen wir auch zu Ihrer Veranstaltung!')

@section('header')
    <header class="background-wrapper background-filter-light" style="min-height: 125vh;">
        <div class="background-image" style="background-image: url({{ asset('images/archive/large/2023_konzert_klang_der_alpen_gruppenfoto.jpg') }});"></div>
        <div class="background-text container d-flex flex-column align-items-center" style="height: 100vh;">
            <div class="my-auto text-center">
                <div class="row">
                    <div class="col col-md-6 text-center my-auto">
                        <h1>Willkommen...</h1>
                        <h2 class="mb-0">...auf der Website des Musikvereins "Musikalische Löwen" Nentershausen&nbsp;e.V.!</h2>
                    </div>
                    <div class="col col-md-6 text-center my-auto">
                        <a title="Bixeworscht und Blosmusik" href="{{ asset('images/archive/large/2025_bixeworscht_plakat.jpg') }}">
                            <img src="{{ asset('images/archive/large/2025_bixeworscht_plakat.jpg') }}" alt="Bixeworscht und Blosmusik" class="mt-3 mb-3" style="height: 70vh;" />
                        </a>
                    </div>
                </div>
            </div>
            <div class="scroll pb-5">
                <a class="text-white" href="#news">
                    <span></span>
                    <span></span>
                    <span></span>
                    Mehr Infos &amp; News
                </a>
            </div>
        </div>
    </header>
@endsection

@section('main')
    <div class="container py-4" id="news">
        <div class="row row-cols-1 row-cols-md-3 g-4" id="lightgallery">
            <div class="col">
                <div class="card shadow-sm bg-primary text-white">
                    <div class="card-body">
                        <p class="card-text mb-3">
                            Wir sind ein junger Musikverein aus Nentershausen im Westerwald und bieten Ihnen Musik für die verschiedensten Anlässe. Gerne kommen wir auch zu Ihrer Veranstaltung,  <a href="{{ url('kontakt') }}">schreiben Sie uns eine Mail oder rufen Sie einfach an</a>!
                        </p>
                        <p class="card-text">
                            Nachfolgend finden Sie ein paar Neuigkeiten aus dem Vereinsleben. Noch mehr Neuigkeiten gibt es auf <a target="_blank" rel="noreferrer" href="https://www.instagram.com/musikalische.loewen/" >Instagram</a>.
                        </p>
                    </div>
                </div>
            </div>
            @foreach(\App\Models\Post::take(5)->get() as $post)
                <div class="col">
                    <div class="card shadow-sm">
                        <a href="{{ asset('storage/'.$post->path_display) }}" class="card-img-wrap">
                            <img src="{{ asset('storage/'.$post->path_thumbnail) }}" class="card-img-top" alt="{{ $post->accessibilityCaption }}">
                        </a>
                        <div class="card-body">
                            <p class="card-text">{{ $post->caption }}</p>
                            <p class="card-text"><small class="text-muted">Veröffentlicht {{ $post->date->diffForHumans()  }}</small></p>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    <!--

      __  __           _ _         _ _          _            _                                      _____                _       _
     |  \/  |         (_) |       | (_)        | |          | |                                    / ____|              (_)     | |
     | \  / |_   _ ___ _| | ____ _| |_ ___  ___| |__   ___  | |     ___   _____      _____ _ __   | (___  _ __   ___ _____  __ _| |
     | |\/| | | | / __| | |/ / _` | | / __|/ __| '_ \ / _ \ | |    / _ \ / _ \ \ /\ / / _ \ '_ \   \___ \| '_ \ / _ \_  / |/ _` | |
     | |  | | |_| \__ \ |   < (_| | | \__ \ (__| | | |  __/ | |___| (_) |  __/\ V  V /  __/ | | |  ____) | |_) |  __// /| | (_| | |
     |_|  |_|\__,_|___/_|_|\_\__,_|_|_|___/\___|_| |_|\___| |______\___/ \___| \_/\_/ \___|_| |_| |_____/| .__/ \___/___|_|\__,_|_|
                                                                                                         | |
                                                                                                         |_|
    Herzlich Glückwunsch! Sie haben das Musikalische Löwen Spezial gefunden!
    Als Gewinn gibt es drei geheime YouTube Links:
    - Musiplantschen auf dem Herthasee: https://www.youtube.com/watch?v=rNR3o-FCjPw
    - Quellkartoffel und Dupp Dupp für vier Clowns: https://www.youtube.com/watch?v=f9ghAKP6IIE
    - Weihnachtsfeier: https://www.youtube.com/watch?v=GSnxeejk9mk
    Viel Spaß damit!

    -->
@endsection

@section('javascript')
    <script type="text/javascript">
        // Initialize lightgallery
        let lightGalleryOptions = {
            selector: '.card-img-wrap',
            download: false,
        };
        lightGallery(document.getElementById('lightgallery'), lightGalleryOptions);
        // Initialize Mansonry
        let masonry = new Masonry(document.getElementById('lightgallery'), {
            itemSelector: '.col',
            percentPosition: true,
        });
        // Layout Masonry after each image loaded
        imagesLoaded(document.getElementById('lightgallery'), function() {
            masonry.layout();
        });
    </script>
@endsection

resources/views/pages/intern.blade.php
@extends('layout.main')

@section('title', 'Intern')
@section('image', asset('images/archive/large/fede-casanova-9HkBtMf_3TU-unsplash.jpg'))
@section('abstract')
    Hier geht's zum internen Bereich für Vereinsmitglieder.
@endsection

@section('background')
    <div class="position-fixed w-100 h-100">
        <div class="background-wrapper background-filter-light h-100">
            <div class="background-image" style="background-image: url('@yield('image')');">
            </div>
        </div>
    </div>
@endsection

@section('header')
    <header class="background-wrapper d-flex align-items-center">
        <div class="background-text container py-5">
            <h1>
                @yield('title')
            </h1>
            <div class="row align-items-start">
                <div class="col col-md-9">
                    <p class="mb-0">
                        @yield('abstract')
                    </p>
                </div>
            </div>
        </div>
    </header>
@endsection

@section('main')
    <div class="container mt-3 mb-5">
        <div class="row">
            <div class="col-md-6 col-lg-4">
                <div class="card shadow-sm bg-primary text-white mt-0 mb-4 py-0">
                    <div class="card-body">
                        <p class="mb-0">Bitte beachten Sie, dass der Login zum Internen Bereich derzeit noch nicht aktiv ist.</p>
                    </div>
                </div>
                <div class="card shadow-sm my-0 py-0">
                    <form method="get" action="#" {{-- TODO: Make a real form with submit button etc. --}} >
                        <div class="card-body">
                            <div class="form-floating mb-3">
                                <input type="email" class="form-control" name="email" id="email" placeholder="max.mustermann@example.com">
                                <label for="email">E-Mail</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" name="password" id="password" placeholder="Passwort">
                                <label for="password">Passwort</label>
                            </div>
                            <button type="button" class="btn btn-primary btn-round btn-block me-3">Anmelden</button>
                            <a href="#">Zugangsdaten vergessen?</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/kontakt.blade.php
@extends('layout.main')

@section('title', 'Kontakt')
@section('image', asset('images/archive/large/rich-smith-685e1B55wr0-unsplash.jpg'))
@section('abstract')
    Möchten Sie ein Orchester für Ihre Veranstaltung buchen?
    Möchten Sie Mitglied in unserem Verein werden?
    Haben Sie eine Frage zum Musikunterricht?
    Dann schreiben Sie uns doch eine Mail oder rufen sie einfach an.
    Wir freuen uns!
@endsection

@section('background')
    <div class="position-fixed w-100 h-100">
        <div class="background-wrapper background-filter-light h-100">
            <div class="background-image" style="background-image: url('@yield('image')');">
            </div>
        </div>
    </div>
@endsection

@section('header')
    <header class="background-wrapper d-flex align-items-center">
        <div class="background-text container py-5">
            <h1>
                @yield('title')
            </h1>
            <div class="row align-items-start">
                <div class="col col-md-9">
                    <p class="mb-0">
                        @yield('abstract')
                    </p>
                </div>
            </div>
        </div>
    </header>
@endsection

@section('main')
    <div class="container mt-3 mb-5">
        <div class="row">
            <div class="col-md-8 col-lg-5">
                <div class="card shadow-sm bg-primary text-white mt-0 mb-4 py-0">
                    <div class="card-body">
                        <p class="mb-0">Sie erreichen uns unter <a class="text-white" href="mailto:{{ config('mail.tox.address') }}">{{ config('mail.tox.address') }}</a>, unter <a class="text-white" href="tel:+4964854300">06485 4300</a> oder über das nachfolgende Kontaktformular.</p>
                    </div>
                </div>
                @if(session('success'))
                <div class="card shadow-sm bg-success text-white mt-0 mb-4 py-0">
                    <div class="card-body">
                        <p class="mb-0">{{ session('success') }}</p>
                    </div>
                </div>
                @endif
                <div class="card shadow-sm my-0 py-0">
                    <form method="post" action="{{ route('forms.contact') }}" >
                        @csrf
                        @honeypot
                        <div class="card-body">
                            <div class="form-floating mb-3 has-validation">
                                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name" placeholder="Max Mustermann" value="{{ old('name') }}" required>
                                <label for="name">Name</label>
                                @include('layout.error', ['name' => 'name'])
                            </div>
                            <div class="form-floating mb-3">
                                <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" id="email" placeholder="max.mustermann@example.com" value="{{ old('email') }}" required>
                                <label for="email">E-Mail</label>
                                @include('layout.error', ['name' => 'email'])
                            </div>
                            <div class="form-floating mb-3">
                                <textarea class="form-control @error('message') is-invalid @enderror" placeholder="Hallo! Ich suche ein Orchester zur musikalischen Begleitung unserer Jubiläumsfeier... " name="message" id="message" style="height: 150px" required>{{ old('message') }}</textarea>
                                <label for="message">Nachricht</label>
                                @include('layout.error', ['name' => 'message'])
                            </div>
                            <button type="submit" class="btn btn-primary btn-round btn-block">Nachricht absenden</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection